from utils import escape_latex

def generate_header(data):
    """Membuat bagian header dokumen LaTeX"""
    header = r"""
%-------------------------
% Resume in Latex - ATS Optimized
% Generated by Streamlit Resume Generator
%------------------------

\documentclass[letterpaper,10.5pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\usepackage{ragged2e}

\pagestyle{fancy}
\fancyhf{} 
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Compact margins
\addtolength{\oddsidemargin}{-0.6in}
\addtolength{\evensidemargin}{-0.6in}
\addtolength{\textwidth}{1.2in}
\addtolength{\topmargin}{-.6in}
\addtolength{\textheight}{1.2in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Consistent sections formatting
\titleformat{\section}{
  \vspace{-5pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

% Custom commands
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}\vspace{-5pt}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}

%----------HEADING----------
\begin{center}
"""
    # Personal Info Section
    header += f"    \\textbf{{\\Huge \\scshape {escape_latex(data['name'])}}} \\\\ \\vspace{{2pt}}\n"
    if data['title']:
        header += f"    \\textbf{{\\Large {escape_latex(data['title'])}}} \\\\ \\vspace{{2pt}}\n"
    
    header += f"    \\small \\href{{mailto:{data['email']}}}{{\\underline{{{escape_latex(data['email'])}}}}} $|$ \n"
    
    # LinkedIn handling
    linkedin_display = data['linkedin'].replace('https://', '').replace('www.', '')
    header += f"    \\href{{{data['linkedin']}}}{{\\underline{{{escape_latex(linkedin_display)}}}}} $|$ \n"
    
    header += f"    \\href{{{data['portfolio']}}}{{\\underline{{Portfolio}}}} $|$ \n"
    header += f"    {escape_latex(data['phone'])}\n"
    header += "\\end{center}\n"
    return header

def generate_summary(summary_text):
    if not summary_text:
        return ""
    
    return r"""
%-----------PROFESSIONAL SUMMARY-----------
\section{\textbf{Summary}}
\begin{justify}
\small
""" + f"{escape_latex(summary_text)}\n" + "\\end{justify}\n"

def generate_education(education_list):
    if not education_list:
        return ""
    
    latex = r"""
%-----------EDUCATION-----------
\section{\textbf{Education}}
\resumeSubHeadingListStart
"""
    for edu in education_list:
        if edu['degree']:
            latex += f"  \\resumeSubheading\n"
            latex += f"    {{{escape_latex(edu['degree'])}}}{{{escape_latex(edu['period'])}}}\n"
            latex += f"    {{{escape_latex(edu['institution'])}}}{{{escape_latex(edu['location'])}}}\n"
    latex += "\\resumeSubHeadingListEnd\n"
    return latex

def generate_experience(experience_list):
    if not experience_list:
        return ""
    
    latex = r"""
%-----------PROFESSIONAL EXPERIENCE-----------
\section{\textbf{Professional Experience}}
\resumeSubHeadingListStart
"""
    for exp in experience_list:
        if exp['position']:
            latex += f"  \\resumeSubheading\n"
            latex += f"    {{{escape_latex(exp['position'])}}}{{{escape_latex(exp['period'])}}}\n"
            latex += f"    {{{escape_latex(exp['company'])}}}{{{escape_latex(exp['location'])}}}\n"
            latex += "    \\resumeItemListStart\n"
            # Split text area by new lines for items
            items = exp['responsibilities'].split('\n')
            for item in items:
                if item.strip():
                    latex += f"      \\resumeItem{{{escape_latex(item.strip())}}}\n"
            latex += "    \\resumeItemListEnd\n"
    latex += "\\resumeSubHeadingListEnd\n"
    return latex

def generate_projects(project_list):
    if not project_list:
        return ""

    latex = r"""
%-----------PROJECTS-----------
\section{\textbf{Key Projects}}
\resumeSubHeadingListStart
"""
    for proj in project_list:
        if proj['title']:
            latex += "    \\resumeProjectHeading\n"
            latex += f"    {{\\textbf{{{escape_latex(proj['title'])}}} $|$ \\emph{{{escape_latex(proj['tech'])}}}}}{{{escape_latex(proj['year'])}}}\n"
            latex += "    \\resumeItemListStart\n"
            items = proj['description'].split('\n')
            for item in items:
                if item.strip():
                    latex += f"      \\resumeItem{{{escape_latex(item.strip())}}}\n"
            latex += "    \\resumeItemListEnd\n"
    latex += "\\resumeSubHeadingListEnd\n"
    return latex

def generate_skills(skills_data):
    if not any(skills_data.values()):
        return ""
    
    latex = r"""
%-----------SKILLS-----------
\section{\textbf{Technical Skills}}
\begin{itemize}[leftmargin=0.15in, label={}]
  \small{
    \item{
"""
    if skills_data['data_analysis']:
        latex += f"     \\textbf{{Data Analysis:}} {escape_latex(skills_data['data_analysis'])} \\\\\n"
    if skills_data['ml']:
        latex += f"     \\textbf{{Machine Learning:}} {escape_latex(skills_data['ml'])} \\\\\n"
    if skills_data['ai']:
        latex += f"     \\textbf{{AI \\& Automation:}} {escape_latex(skills_data['ai'])} \\\\\n"
    if skills_data['business']:
        latex += f"     \\textbf{{Business Skills:}} {escape_latex(skills_data['business'])}\n"
    
    latex += r"""    }
  }
\end{itemize}
"""
    return latex

def generate_certifications(cert_list):
    if not any(c.strip() for c in cert_list):
        return ""

    latex = r"""
%-----------ACHIEVEMENTS-----------
\section{\textbf{Certifications \& Honors}}
\begin{itemize}[leftmargin=0.15in, label={}]
  \small{
"""
    for cert in cert_list:
        if cert.strip():
            latex += f"    \\item{{$\\bullet$ {escape_latex(cert.strip())}}}\n"
    latex += "  }\n\\end{itemize}\n"
    return latex

def generate_languages(lang_list):
    if not any(l.strip() for l in lang_list):
        return ""

    latex = r"""
%-----------LANGUAGES-----------
\section{\textbf{Languages}}
\begin{itemize}[leftmargin=0.15in, label={}]
  \small{
"""
    for lang in lang_list:
        if lang.strip():
            latex += f"    \\item{{$\\bullet$ {escape_latex(lang.strip())}}}\n"
    latex += "  }\n\\end{itemize}\n"
    return latex

def generate_full_latex(data):
    """Menggabungkan semua bagian menjadi satu dokumen lengkap"""
    doc = generate_header(data)
    doc += generate_summary(data['summary'])
    doc += generate_education(data['education'])
    doc += generate_experience(data['experience'])
    doc += generate_projects(data['projects'])
    doc += generate_skills(data['skills'])
    doc += generate_certifications(data['certifications'])
    doc += generate_languages(data['languages'])
    doc += "\n\\end{document}"
    return doc