import streamlit as st
import datetime

# --- KONFIGURASI HALAMAN ---
st.set_page_config(
    page_title="LaTeX Resume Generator",
    page_icon="📄",
    layout="wide"
)

# --- FUNGSI HELPER ---

def escape_latex(text):
    """
    Melakukan escaping pada karakter spesial LaTeX agar tidak error saat dicompile.
    """
    if not text:
        return ""
    
    # Mapping karakter spesial LaTeX
    replacements = {
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
        '\\': r'\textbackslash{}'
    }
    
    # Lakukan replace karakter
    escaped_text = "".join(replacements.get(char, char) for char in text)
    return escaped_text

def init_session_state():
    """Menginisialisasi state untuk jumlah item dinamis (max 5)"""
    if 'edu_count' not in st.session_state: st.session_state.edu_count = 1
    if 'exp_count' not in st.session_state: st.session_state.exp_count = 1
    if 'proj_count' not in st.session_state: st.session_state.proj_count = 1
    if 'cert_count' not in st.session_state: st.session_state.cert_count = 1
    if 'lang_count' not in st.session_state: st.session_state.lang_count = 1

def manage_count(key, operation, max_val=5):
    """Mengatur penambahan/pengurangan item"""
    if operation == 'add' and st.session_state[key] < max_val:
        st.session_state[key] += 1
    elif operation == 'remove' and st.session_state[key] > 0:
        st.session_state[key] -= 1

# --- FUNGSI GENERATOR LATEX ---

def generate_latex_code(data):
    """Menghasilkan string lengkap kode LaTeX berdasarkan input user"""
    
    # Template Header (Preamble)
    latex = r"""
%-------------------------
% Resume in Latex - ATS Optimized
% Generated by Streamlit Resume Generator
%------------------------

\documentclass[letterpaper,10.5pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\usepackage{ragged2e}

\pagestyle{fancy}
\fancyhf{} 
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Compact margins
\addtolength{\oddsidemargin}{-0.6in}
\addtolength{\evensidemargin}{-0.6in}
\addtolength{\textwidth}{1.2in}
\addtolength{\topmargin}{-.6in}
\addtolength{\textheight}{1.2in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Consistent sections formatting
\titleformat{\section}{
  \vspace{-5pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

% Custom commands
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}\vspace{-5pt}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}

%----------HEADING----------
\begin{center}
"""
    # Personal Info Section
    latex += f"    \\textbf{{\\Huge \\scshape {escape_latex(data['name'])}}} \\\\ \\vspace{{2pt}}\n"
    if data['title']:
        latex += f"    \\textbf{{\\Large {escape_latex(data['title'])}}} \\\\ \\vspace{{2pt}}\n"
    
    latex += f"    \\small \\href{{mailto:{data['email']}}}{{\\underline{{{escape_latex(data['email'])}}}}} $|$ \n"
    
    linkedin_display = data['linkedin'].replace('https://', '').replace('www.', '')
    latex += f"    \\href{{{data['linkedin']}}}{{\\underline{{{escape_latex(linkedin_display)}}}}} $|$ \n"
    
    latex += f"    \\href{{{data['portfolio']}}}{{\\underline{{Portfolio}}}} $|$ \n"
    latex += f"    {escape_latex(data['phone'])}\n"
    latex += "\\end{center}\n"

    # Summary
    if data['summary']:
        latex += r"""
%-----------PROFESSIONAL SUMMARY-----------
\section{\textbf{Summary}}
\begin{justify}
\small
"""
        latex += f"{escape_latex(data['summary'])}\n"
        latex += "\\end{justify}\n"

    # Education
    if data['education']:
        latex += r"""
%-----------EDUCATION-----------
\section{\textbf{Education}}
\resumeSubHeadingListStart
"""
        for edu in data['education']:
            if edu['degree']:
                latex += f"  \\resumeSubheading\n"
                latex += f"    {{{escape_latex(edu['degree'])}}}{{{escape_latex(edu['period'])}}}\n"
                latex += f"    {{{escape_latex(edu['institution'])}}}{{{escape_latex(edu['location'])}}}\n"
        latex += "\\resumeSubHeadingListEnd\n"

    # Experience
    if data['experience']:
        latex += r"""
%-----------PROFESSIONAL EXPERIENCE-----------
\section{\textbf{Professional Experience}}
\resumeSubHeadingListStart
"""
        for exp in data['experience']:
            if exp['position']:
                latex += f"  \\resumeSubheading\n"
                latex += f"    {{{escape_latex(exp['position'])}}}{{{escape_latex(exp['period'])}}}\n"
                latex += f"    {{{escape_latex(exp['company'])}}}{{{escape_latex(exp['location'])}}}\n"
                latex += "    \\resumeItemListStart\n"
                # Split text area by new lines for items
                items = exp['responsibilities'].split('\n')
                for item in items:
                    if item.strip():
                        latex += f"      \\resumeItem{{{escape_latex(item.strip())}}}\n"
                latex += "    \\resumeItemListEnd\n"
        latex += "\\resumeSubHeadingListEnd\n"

    # Projects
    if data['projects']:
        latex += r"""
%-----------PROJECTS-----------
\section{\textbf{Key Projects}}
\resumeSubHeadingListStart
"""
        for proj in data['projects']:
            if proj['title']:
                latex += "    \\resumeProjectHeading\n"
                latex += f"    {{\\textbf{{{escape_latex(proj['title'])}}} $|$ \\emph{{{escape_latex(proj['tech'])}}}}}{{{escape_latex(proj['year'])}}}\n"
                latex += "    \\resumeItemListStart\n"
                items = proj['description'].split('\n')
                for item in items:
                    if item.strip():
                        latex += f"      \\resumeItem{{{escape_latex(item.strip())}}}\n"
                latex += "    \\resumeItemListEnd\n"
        latex += "\\resumeSubHeadingListEnd\n"

    # Skills
    if any(data['skills'].values()):
        latex += r"""
%-----------SKILLS-----------
\section{\textbf{Technical Skills}}
\begin{itemize}[leftmargin=0.15in, label={}]
  \small{
    \item{
"""
        if data['skills']['data_analysis']:
            latex += f"     \\textbf{{Data Analysis:}} {escape_latex(data['skills']['data_analysis'])} \\\\\n"
        if data['skills']['ml']:
            latex += f"     \\textbf{{Machine Learning:}} {escape_latex(data['skills']['ml'])} \\\\\n"
        if data['skills']['ai']:
            latex += f"     \\textbf{{AI \\& Automation:}} {escape_latex(data['skills']['ai'])} \\\\\n"
        if data['skills']['business']:
            latex += f"     \\textbf{{Business Skills:}} {escape_latex(data['skills']['business'])}\n"
        
        latex += r"""    }
  }
\end{itemize}
"""

    # Certifications
    if any(c.strip() for c in data['certifications']):
        latex += r"""
%-----------ACHIEVEMENTS-----------
\section{\textbf{Certifications \& Honors}}
\begin{itemize}[leftmargin=0.15in, label={}]
  \small{
"""
        for cert in data['certifications']:
            if cert.strip():
                latex += f"    \\item{{$\\bullet$ {escape_latex(cert.strip())}}}\n"
        latex += "  }\n\\end{itemize}\n"

    # Languages
    if any(l.strip() for l in data['languages']):
        latex += r"""
%-----------LANGUAGES-----------
\section{\textbf{Languages}}
\begin{itemize}[leftmargin=0.15in, label={}]
  \small{
"""
        for lang in data['languages']:
            if lang.strip():
                latex += f"    \\item{{$\\bullet$ {escape_latex(lang.strip())}}}\n"
        latex += "  }\n\\end{itemize}\n"

    # End Document
    latex += "\n\\end{document}"
    
    return latex

# --- UI UTAMA ---

def main():
    init_session_state()

    # Sidebar: Instruksi
    with st.sidebar:
        st.header("📌 Cara Penggunaan")
        st.info("""
        1. **Isi Form**: Lengkapi data di tab sebelah kanan. Kolom bertanda (*) wajib diisi.
        2. **Generate**: Jika semua data wajib terisi, kode LaTeX akan muncul di bagian bawah.
        3. **Copy Code**: Salin kode yang dihasilkan.
        4. **Buka Overleaf**: Pergi ke [Overleaf.com](https://www.overleaf.com).
        5. **New Project**: Buat 'Blank Project'.
        6. **Paste & Compile**: Tempel kode di editor Overleaf dan klik 'Recompile'.
        7. **Download PDF**: Unduh hasil resume PDF Anda.
        """)
        st.warning("⚠️ Fitur: Maksimal 5 item untuk Pendidikan, Pengalaman, dan Project agar muat di 1 halaman.")

    st.title("📄 LaTeX Resume Generator")

    # --- FORM INPUT ---
    with st.form("resume_form"):
        st.subheader("1. Informasi Dasar (Wajib *)")
        col1, col2 = st.columns(2)
        with col1:
            name = st.text_input("Nama Lengkap *", placeholder="Contoh: Budi Santoso")
            title = st.text_input("Judul/Posisi yang Dilamar", placeholder="Contoh: Data Analyst")
            email = st.text_input("Email *", placeholder="email@contoh.com")
        with col2:
            phone = st.text_input("Nomor Telepon *", placeholder="0812-3456-7890")
            linkedin = st.text_input("Link LinkedIn *", placeholder="https://linkedin.com/in/budisantoso")
            portfolio = st.text_input("Link Portfolio *", placeholder="https://budisantoso.com")
        
        st.subheader("2. Professional Summary")
        summary = st.text_area("Ringkasan Diri", placeholder="Jelaskan secara singkat pengalaman dan keahlian Anda...", height=100)

        # --- EDUCATION (Dynamic) ---
        st.markdown("---")
        st.subheader("3. Pendidikan (Max 5)")
        education_data = []
        for i in range(st.session_state.edu_count):
            st.markdown(f"**Pendidikan #{i+1}**")
            c1, c2, c3, c4 = st.columns(4)
            deg = c1.text_input(f"Gelar #{i+1}", placeholder="B.Sc Computer Science")
            inst = c2.text_input(f"Institusi #{i+1}", placeholder="Universitas Indonesia")
            loc = c3.text_input(f"Kota #{i+1}", placeholder="Depok, Indonesia")
            per = c4.text_input(f"Periode #{i+1}", placeholder="2020 -- 2024")
            if deg and inst:
                education_data.append({'degree': deg, 'institution': inst, 'location': loc, 'period': per})
        
        ce1, ce2 = st.columns([1, 5])
        with ce1:
            add_edu = st.form_submit_button("➕ Tambah Pendidikan")
        if add_edu:
            manage_count('edu_count', 'add')
            st.rerun()

        # --- EXPERIENCE (Dynamic) ---
        st.markdown("---")
        st.subheader("4. Pengalaman Kerja (Max 5)")
        experience_data = []
        for i in range(st.session_state.exp_count):
            st.markdown(f"**Pengalaman #{i+1}**")
            c1, c2 = st.columns(2)
            role = c1.text_input(f"Posisi #{i+1}", placeholder="Junior Developer")
            comp = c2.text_input(f"Perusahaan #{i+1}", placeholder="Tokopedia")
            c3, c4 = st.columns(2)
            loc = c3.text_input(f"Lokasi Kerja #{i+1}", placeholder="Jakarta")
            per = c4.text_input(f"Periode Kerja #{i+1}", placeholder="Jan 2023 -- Sekarang")
            resp = st.text_area(f"Tanggung Jawab #{i+1} (Satu poin per baris)", placeholder="- Membuat fitur baru\n- Optimasi database", height=100)
            
            if role and comp:
                experience_data.append({'position': role, 'company': comp, 'location': loc, 'period': per, 'responsibilities': resp})

        cx1, cx2 = st.columns([1, 5])
        with cx1:
            add_exp = st.form_submit_button("➕ Tambah Pengalaman")
        if add_exp:
            manage_count('exp_count', 'add')
            st.rerun()

        # --- PROJECTS (Dynamic) ---
        st.markdown("---")
        st.subheader("5. Proyek (Max 5)")
        project_data = []
        for i in range(st.session_state.proj_count):
            st.markdown(f"**Proyek #{i+1}**")
            c1, c2 = st.columns([3, 1])
            title_proj = c1.text_input(f"Nama Proyek #{i+1}", placeholder="Sistem Prediksi Harga Rumah")
            year_proj = c2.text_input(f"Tahun #{i+1}", placeholder="2024")
            tech_proj = st.text_input(f"Teknologi #{i+1}", placeholder="Python, Scikit-Learn, Streamlit")
            desc_proj = st.text_area(f"Deskripsi Proyek #{i+1} (Satu poin per baris)", placeholder="- Mengembangkan model ML dengan akurasi 95%", height=80)
            
            if title_proj:
                project_data.append({'title': title_proj, 'year': year_proj, 'tech': tech_proj, 'description': desc_proj})

        cp1, cp2 = st.columns([1, 5])
        with cp1:
            add_proj = st.form_submit_button("➕ Tambah Proyek")
        if add_proj:
            manage_count('proj_count', 'add')
            st.rerun()

        # --- SKILLS ---
        st.markdown("---")
        st.subheader("6. Keahlian (Skills)")
        sk1, sk2 = st.columns(2)
        s_data = sk1.text_input("Data Analysis Skills", placeholder="Python (Pandas), SQL, Excel")
        s_ml = sk2.text_input("Machine Learning Skills", placeholder="Scikit-Learn, TensorFlow")
        s_ai = sk1.text_input("AI & Automation", placeholder="LLM, Selenium, Zapier")
        s_biz = sk2.text_input("Business Skills", placeholder="Communication, Project Management")
        
        skills_data = {
            'data_analysis': s_data, 'ml': s_ml, 'ai': s_ai, 'business': s_biz
        }

        # --- CERTIFICATIONS & LANGUAGES ---
        st.markdown("---")
        col_c, col_l = st.columns(2)
        
        with col_c:
            st.subheader("7. Sertifikasi")
            cert_list = []
            for i in range(st.session_state.cert_count):
                cert = st.text_input(f"Sertifikat #{i+1}", key=f"cert_{i}")
                cert_list.append(cert)
            if st.form_submit_button("➕ Sertifikat"):
                manage_count('cert_count', 'add')
                st.rerun()

        with col_l:
            st.subheader("8. Bahasa")
            lang_list = []
            for i in range(st.session_state.lang_count):
                lang = st.text_input(f"Bahasa #{i+1}", key=f"lang_{i}")
                lang_list.append(lang)
            if st.form_submit_button("➕ Bahasa"):
                manage_count('lang_count', 'add')
                st.rerun()

        # --- FINAL SUBMIT ---
        st.markdown("---")
        submitted = st.form_submit_button("🚀 GENERATE LATEX CODE", type="primary")

    # --- OUTPUT LOGIC ---
    if submitted:
        # Validasi Input Wajib
        if not (name and email and linkedin and portfolio and phone):
            st.error("❌ Mohon lengkapi semua data wajib di bagian Informasi Dasar!")
        else:
            # Susun Data
            full_data = {
                'name': name,
                'title': title,
                'email': email,
                'linkedin': linkedin,
                'portfolio': portfolio,
                'phone': phone,
                'summary': summary,
                'education': education_data,
                'experience': experience_data,
                'projects': project_data,
                'skills': skills_data,
                'certifications': cert_list,
                'languages': lang_list
            }

            # Generate Code
            latex_code = generate_latex_code(full_data)
            
            # Tampilkan Hasil
            st.success("✅ Kode berhasil dibuat! Silakan salin kode di bawah ini:")
            st.code(latex_code, language='latex')
            
            # Download Button
            st.download_button(
                label="📥 Download File .tex",
                data=latex_code,
                file_name="resume.tex",
                mime="text/x-tex"
            )

if __name__ == "__main__":
    main()